services:
  astt-software-backend-service:
    container_name: astt-software-backend-container
    image: astt-software-backend-image
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  astt-software-frontend-service:
    container_name: astt-software-frontend-container
    image: astt-software-frontend-image
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
      - frontend-node-modules:/app/node_modules
    depends_on:
      - astt-software-backend-service

volumes:
  frontend-node-modules:
